### ISSUE TITLE
FYSETC F6 v1.3 pin mapping error

### ISSUE THREAD

**Issue by joris57** [trevjonez/klipper-configs#2]
The FYSETC F6 v1.3 pin mapping was a great help. However, I think there's an error in the E0 line, which, I believe, should read: 

'# E0 step: PA4, dir: PA6, enable: PA2, cs: PL2, diag: PE4

**Comment by trevjonez** [comment]
finally circling back on this. I can't even remember where I came up with those E0, E1, E2 diag pin values. what was your path for finding them?

**Comment by trevjonez** [comment]
You are correct, I just went through the board with my DMM and confirmed that E0 diag is PE4 via the Z+ jumper

**Comment by trevjonez** [comment]
updated the two F6 files I have here
