### ISSUE TITLE
Would this work for the following thermistor?

### ISSUE THREAD

**Issue by johnrobledo** [trevjonez/klipper-configs#4]
Hello. Would this config work for [this](https://www.amazon.com/gp/product/B0888NJ63W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) thermistor? Also, do you know what to put for "sensor type?"

**Comment by trevjonez** [comment]
I think it should work. type is not required when using thermistor instead of temperature_sensor

https://www.klipper3d.org/Config_Reference.html#thermistor
